'use client';
import Link from 'next/link'; import {usePathname} from 'next/navigation'; import {useEffect,useState} from 'react';
import {logout,getStoredUser,me} from '../lib/api'; import {AuthGate} from './auth-gate';
import {LayoutDashboard,ReceiptText,WalletCards,ChartNoAxesCombined,Package,Smartphone,HandCoins,Users,Receipt,UserRoundCog,Settings,Menu,Search,Bell,Plus,ChevronDown} from 'lucide-react';
const nav=[
 {label:'Dashboard',href:'/dashboard',icon:LayoutDashboard},
 {label:'Transaksi',href:'/transaksi/baru',icon:ReceiptText,children:[['Transaksi Baru','/transaksi/baru'],['Hari Ini','/transaksi/laporan-harian']]},
 {label:'Kasir',href:'/kasir',icon:WalletCards},{label:'Laporan',href:'/laporan',icon:ChartNoAxesCombined},{label:'Barang',href:'/barang',icon:Package},{label:'Service HP',href:'/service-hp',icon:Smartphone},{label:'KASBON',href:'/kasbon',icon:HandCoins},{label:'Pelanggan',href:'/pelanggan',icon:Users},{label:'Pengeluaran',href:'/pengeluaran',icon:Receipt},{label:'Karyawan & Gaji',href:'/karyawan',icon:UserRoundCog},{label:'Pengaturan',href:'/pengaturan/theme',icon:Settings}
];
export function AppShell({children}:{children:React.ReactNode}){const p=usePathname(); const [user,setUser]=useState<any>(null); useEffect(()=>{if(p==='/login')return;const u=getStoredUser();if(u)setUser(u);me().then(setUser).catch(()=>{})},[p]); if(p==='/login')return <>{children}</>;
 return <AuthGate><>
  <aside className="sidebar fixed inset-y-0 left-0 z-30 flex w-[248px] flex-col bg-[var(--sidebar)] text-white">
   <div className="flex h-16 items-center gap-3 border-b border-white/10 px-5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-teal-500 font-black">I</div><div className="sidebar-label"><div className="text-sm font-bold">IRKOP CELL</div><div className="text-[11px] text-slate-400">Dashboard & Kasir</div></div></div>
   <div className="flex-1 overflow-y-auto px-3 py-4"><div className="sidebar-label mb-2 px-2 text-[10px] font-semibold uppercase tracking-widest text-slate-500">Menu utama</div>{nav.map((n:any)=>{const active=p===n.href||p.startsWith(n.href+'/');const Icon=n.icon;return <div key={n.label}><Link href={n.href} className={'nav-item mb-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition '+(active?'bg-white/10 text-white':'text-slate-300 hover:bg-white/5 hover:text-white')}><Icon size={18}/><span className="sidebar-label flex-1">{n.label}</span>{n.children&&<ChevronDown size={14} className="sidebar-label"/>}</Link>{n.children&&active&&<div className="sidebar-label ml-10 mb-2 space-y-1">{n.children.map((c:any)=><Link key={c[1]} href={c[1]} className="block rounded-lg px-2 py-1.5 text-xs text-slate-400 hover:text-white">{c[0]}</Link>)}</div>}</div>})}</div>
   <div className="border-t border-white/10 p-3"><div className="flex items-center gap-3 rounded-xl bg-white/5 px-3 py-2.5"><div className="grid h-8 w-8 place-items-center rounded-full bg-slate-700 text-xs font-bold">{(user?.name||user?.email||'U').slice(0,2).toUpperCase()}</div><div className="sidebar-label min-w-0"><div className="truncate text-xs font-semibold">{user?.name||user?.email||'User'}</div><div className="text-[10px] text-slate-400">{user?.role||'—'}</div></div></div><button onClick={()=>logout().then(()=>location.href='/login')} className="mt-2 w-full rounded-xl border border-white/10 px-3 py-2 text-[11px] text-slate-300 hover:bg-white/5">Keluar</button></div>
  </aside>
  <header className="topbar fixed left-[248px] right-0 top-0 z-20 flex h-16 items-center justify-between border-b border-[var(--line)] bg-white/90 px-6 backdrop-blur"><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Menu size={20}/></button><div className="relative desktop-only"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input placeholder="Cari transaksi, barang, pelanggan..." className="w-72 rounded-xl border border-[var(--line)] bg-slate-50 py-2 pl-9 pr-3 text-xs outline-none focus:border-teal-500"/></div></div><div className="flex items-center gap-3"><div className="hidden rounded-xl bg-emerald-50 px-3 py-2 text-[11px] font-semibold text-emerald-700 sm:block">● Sesi kasir</div><button className="relative rounded-xl p-2.5 hover:bg-slate-100"><Bell size={18}/></button><Link href="/transaksi/baru" className="hidden items-center gap-2 rounded-xl bg-teal-600 px-3 py-2 text-xs font-semibold text-white shadow-sm hover:bg-teal-700 sm:flex"><Plus size={15}/>Transaksi</Link></div></header>
  <main className="main-shell ml-[248px] min-h-screen pt-16"><div className="content p-6">{children}</div></main>
 </></AuthGate>}
