'use client';
import {useEffect,useMemo,useState} from 'react'; import {createResource,deleteResource,listResource,updateResource} from '../lib/api'; import {Card,PageHeader,Toolbar} from './ui'; import {Pencil,Plus,Trash2,X} from 'lucide-react';
export type Field={key:string;label:string;type?:'text'|'number'|'date'|'select';required?:boolean;options?:{value:string;label:string}[]};
function arr(json:any){const x=json?.data??json?.result??json; return Array.isArray(x)?x:(x?.items||x?.rows||x?.data||[])}
export function ResourceCrud({title,desc,path,fields,columns,initial}:{title:string;desc:string;path:string;fields:Field[];columns:{key:string;label:string;format?:(v:any,row:any)=>React.ReactNode}[];initial?:any[]}){
 const [rows,setRows]=useState<any[]>(initial||[]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState<any|null>(null),[form,setForm]=useState<any>({}),[loading,setLoading]=useState(!initial),[error,setError]=useState('');
 async function load(){setLoading(true);try{setRows(arr(await listResource(path)))}catch(e:any){setError(e.message||'Gagal memuat data')}finally{setLoading(false)}}
 useEffect(()=>{if(!initial)load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 function start(row?:any){setEditing(row||null);const next:any={};fields.forEach(f=>next[f.key]=row?.[f.key]??'');setForm(next);setOpen(true);setError('')}
 async function save(e:React.FormEvent){e.preventDefault();setError('');try{const res=editing?await updateResource(`${path}/${editing.id}`,form):await createResource(path,form);const item=(res as any)?.data??(res as any)?.result??res;if(editing)setRows(x=>x.map(r=>r.id===editing.id?(item?.id?item:{...r,...form}):r));else setRows(x=>[item?.id?item:{...form,id:Date.now()},...x]);setOpen(false)}catch(e:any){setError(e.message||'Gagal menyimpan')}}
 async function remove(id:any){if(!confirm('Hapus data ini?'))return;try{await deleteResource(`${path}/${id}`);setRows(x=>x.filter(r=>r.id!==id))}catch(e:any){setError(e.message||'Gagal menghapus')}}
 return <><PageHeader title={title} desc={desc} action={<button onClick={()=>start()} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-xs font-semibold text-white"><Plus size={15}/>Tambah</button>}/><Toolbar searchPlaceholder="Cari..." onSearch={setQ}/>{error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error}</div>}<Card><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b text-slate-500"><tr>{columns.map(c=><th key={c.key} className="pb-3">{c.label}</th>)}<th className="pb-3 text-right">Aksi</th></tr></thead><tbody>{loading?<tr><td colSpan={columns.length+1} className="py-8 text-center text-slate-400">Memuat dari D1…</td></tr>:filtered.map(r=><tr key={r.id} className="border-b border-slate-50">{columns.map(c=><td key={c.key} className="py-3">{c.format?c.format(r[c.key],r):r[c.key]??'-'}</td>)}<td className="py-3 text-right"><div className="inline-flex gap-1"><button onClick={()=>start(r)} className="rounded-lg border p-2"><Pencil size={13}/></button><button onClick={()=>remove(r.id)} className="rounded-lg border p-2 text-rose-600"><Trash2 size={13}/></button></div></td></tr>)}</tbody></table></div></Card>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-2xl bg-white p-5 shadow-xl"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">{editing?'Edit':'Tambah'} {title}</h2><p className="text-xs text-slate-500">Disimpan melalui Central API → D1</p></div><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="space-y-3">{fields.map(f=><label key={f.key} className="block text-xs font-semibold">{f.label}{f.type==='select'?<select required={f.required} value={form[f.key]} onChange={e=>setForm({...form,[f.key]:e.target.value})} className="mt-1 w-full rounded-xl border p-3 text-sm"><option value="">Pilih…</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input required={f.required} type={f.type||'text'} value={form[f.key]} onChange={e=>setForm({...form,[f.key]:f.type==='number'?Number(e.target.value):e.target.value})} className="mt-1 w-full rounded-xl border p-3 text-sm"/>}</label>)}</div>{error&&<div className="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error}</div>}<button className="mt-5 w-full rounded-xl bg-slate-900 py-3 text-sm font-bold text-white">Simpan</button></form></div>}</>
}
